config/routes.rb
    resource :itemwish, module: :collectibles
    resource :itemown, module: :collectibles
    resource :itemsale, module: :collectibles
  end

  post '/rate' => 'rater#create', :as => 'rate'
  resources :books do
    get "books/:page", :action => :index, :on => :collection
    get :autocomplete_book_title, :on => :collection
    get :autocomplete_book_writer, :on => :collection
    get :autocomplete_book_writer2, :on => :collection
    get :autocomplete_book_artist, :on => :collection
    get :autocomplete_book_artist2, :on => :collection
    get :autocomplete_book_colors, :on => :collection
    get :autocomplete_book_cover, :on => :collection
    get :autocomplete_book_letters, :on => :collection
    get :autocomplete_book_editor, :on => :collection
    get :autocomplete_book_eic, :on => :collection
    get :autocomplete_book_country, :on => :collection
    get :autocomplete_book_publisher, :on => :collection
    get :autocomplete_book_imprint, :on => :collection
    get :autocomplete_book_retailer, :on => :collection
    get :autocomplete_book_convention, :on => :collection
    resources :comments
    collection do
      post :import
      get :autocomplete

      # Valiant
      get "valiant/keys" => "books#valiantkeys"
      get "valiant/all" => "books#valiantall"
      get "valiant/all/table" => "books#valiantalltbl"
      get "valiant/all/missing" => "books#valiantallmissing"
      get "valiant/all/table/missing" => "books#valiantalltblmissing"
      get "valiant/sketch" => "books#valiantsketch"
      get "valiant/sketch/table" => "books#valiantsketchtbl"
      get "valiant/trades" => "books#valianttrades"
      get "valiant/trades/table" => "books#valianttradestbl"

      # VH1 Valiant
      get "valiant/classic/all" => "books#valiantvh1all"
      get "valiant/classic/all/table" => "books#valiantvh1alltbl"
      get "valiant/classic/keys" => "books#valiantvh1keys"
      get "valiant/classic/all/missing" => "books#valiantvh1allmissing"
      get "valiant/classic/all/table/missing" => "books#valiantvh1alltblmissing"

      # VH2 Valiant
      get "valiant/acclaim/all" => "books#valiantvh2all"
      get "valiant/acclaim/all/table" => "books#valiantvh2alltbl"
      get "valiant/acclaim/all/missing" => "books#valiantvh2allmissing"
      get "valiant/acclaim/all/table/missing" => "books#valiantvh2alltblmissing"

      # International Valiant
      get "valiant/brazil/all" => "books#valiantbrazil"
      get "valiant/brazil/table" => "books#valiantbraziltbl"
      get "valiant/brazil/missing" => "books#valiantbrazilmissing"
      get "valiant/brazil/table/missing" => "books#valiantbraziltblmissing"
      get "valiant/canada/all" => "books#valiantcanada"
      get "valiant/canada/table" => "books#valiantcanadatbl"
      get "valiant/canada/missing" => "books#valiantcanadamissing"
      get "valiant/canada/table/missing" => "books#valiantcanadatblmissing"
      get "valiant/china/all" => "books#valiantchina"
      get "valiant/china/table" => "books#valiantchinatbl"
      get "valiant/china/missing" => "books#valiantchinamissing"
      get "valiant/china/table/missing" => "books#valiantchinatblmissing"
      get "valiant/france/all" => "books#valiantfrance"
      get "valiant/france/table" => "books#valiantfrancetbl"
      get "valiant/france/missing" => "books#valiantfrancemissing"
      get "valiant/france/table/missing" => "books#valiantfrancetblmissing"
      get "valiant/italy/all" => "books#valiantitaly"
      get "valiant/italy/table" => "books#valiantitalytbl"
      get "valiant/italy/missing" => "books#valiantitalymissing"
      get "valiant/italy/table/missing" => "books#valiantitalytblmissing"
      get "valiant/japan/all" => "books#valiantjapan"
      get "valiant/japan/table" => "books#valiantjapantbl"
      get "valiant/japan/missing" => "books#valiantjapanmissing"
      get "valiant/japan/table/missing" => "books#valiantjapantblmissing"
      get "valiant/mexico/all" => "books#valiantmexico"
      get "valiant/mexico/table" => "books#valiantmexicotbl"
      get "valiant/mexico/missing" => "books#valiantmexicomissing"
      get "valiant/mexico/table/missing" => "books#valiantmexicotblmissing"
      get "valiant/russia/all" => "books#valiantrussia"
      get "valiant/russia/table" => "books#valiantrussiatbl"
      get "valiant/russia/missing" => "books#valiantrussiamissing"
      get "valiant/russia/table/missing" => "books#valiantrussiatblmissing"
      get "valiant/turkey/all" => "books#valiantturkey"
      get "valiant/turkey/table" => "books#valiantturkeytbl"
      get "valiant/turkey/missing" => "books#valiantturkeymissing"
      get "valiant/turkey/table/missing" => "books#valiantturkeytblmissing"

      # Events Valiant
      get "valiant/events/4001ad" => "books#valiantevent4001ad"
      get "valiant/events/harbingerwars" => "books#valianteventshw"
      get "valiant/events/armorhunters" => "books#valianteventsah"
      get "valiant/events/bookofdeath" => "books#valianteventsbod"
      get "valiant/events/unity" => "books#valianteventsunity"
      get "valiant/events/chaoseffect" => "books#valianteventschaoseffect"
      get :manage
    end
    resource :wish, module: :books
    resource :own, module: :books
    resource :sale, module: :books
  end

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'omniauth_callbacks', sessions: 'sessions' }, :path => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  match '/users/:id' => 'users#destroy', :via => [:delete], :as => :admin_destroy_user
  match '/users/:id/profile' => "users#show", via: [:get], :as => 'profile'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/all' => 'users#all', via: [:get]
  match '/users/backers' => 'users#backers', via: [:get]
  match '/users/top25' => 'users#valianttop25', via: [:get]
  match '/users/leaderboard' => 'users#leaderboard', via: [:get]
  match '/users/:id/followers' => "users#followers", via: [:get], :as => 'followers'
  match '/users/:id/following' => "users#following", via: [:get], :as => 'following'
  get 'users/:id/notes' => 'books#mynotes', :as => 'notes'
  get 'users/:id/collection' => 'books#mybooks', :as => 'collection'
  get 'users/:id/collection/table' => 'books#mybookstbl', :as => 'collection_table'
  get 'users/:id/wishlist' => 'books#mywishlist', :as => 'wishlist'
  get 'users/:id/wishlist/table' => 'books#mywishlisttbl', :as => 'wishlist_table'
  get 'users/:id/forsale' => 'books#forsale', :as => 'forsale'
  get 'users/:id/forsale/table' => 'books#forsaletbl', :as => 'forsale_table'
  get 'users/emails' => 'users#emails', via: [:get]
  match 'follow' => 'users#follow', via: [:get]
  match 'unfollow' => 'users#unfollow', via: [:get]
  get 'switch_user' => 'switch_user#set_current_user'

  # Releases
  get 'nextweek' => 'books#thisweek'
  get 'releases/thisweek' => 'books#thisweek'
  get 'releases/currentweek' => 'books#currentweek'
  get 'releases/nextweek' => 'books#nextweek'
  get 'releases/solicitations' => 'books#solicitations'
  get 'releases/lastmonth' => 'books#lastmonth'
  get 'releases/thismonth' => 'books#thismonth'
  get 'releases/nextmonth' => 'books#nextmonth'
  get 'releases/twomonths' => 'books#monthafter'
  get 'releases/latestsolicitations' => 'books#latestsolicits'
  get 'releases/veibydate' => 'books#valiantreleasedate'
  get 'releases/veibydate/table' => 'books#valiantreleasedatetbl'
  get 'timelines/valiant' => 'pages#veitimeline'
  get 'releases/vh1bydate' => 'books#valiantvh1releasedate'
  get 'releases/vh1bydate/table' => 'books#valiantvh1releasedatetbl'
  get 'changelog' => 'pages#changelog'
  get 'supportus' => 'pages#supportus'

  # Sales
  get 'sales/monthly' => 'books#monthlysales'
  get 'sales/yearly' => 'books#yearlysales'
  get 'sales/marketshare' => 'pages#marketshare'
  get 'sales/vei' => 'books#valiantsalesvei'
  get 'sales/veibytitle' => 'books#valiantsalestitle'
  get 'sales/statistics' => 'books#valiantsalesstats'
  get 'sales/titlestatistics' => 'books#valiantsalesstatstitle'
  get 'sales/topselling' => 'books#valianttopselling'
  get 'values/topvalues' => 'books#valianttopvalues'
  get 'values/rankings' => 'books#valiantvalues'
  get 'values/missing' => 'books#valiantvaluesmissing'
  get 'feed' => 'books#feed'
  get 'allfeed' => 'books#allfeed'

  resources "contacts", only: [:new, :create]
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'search' => 'pages#search'
  get 'userlevels' => 'pages#levels'
  get 'news' => 'feeds#news', as: :news
  get 'chat' => 'pages#chat', as: :chat

  match 'sitemap', :to => 'sitemap#index', :via => [:get]

  # Mailbox routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "empty_trash", to: "conversations#empty_trash"

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root :to => 'pages#home'

  # Require authentication to access Sidekiq dashboard
  authenticate :user, lambda { |u| u.admin? } do
    if Rails.env.production?
      mount Sidekiq::Web, at: '/sidekiq'
    end
    get 'stats' => 'users#admin', :as => 'user_statistics'
  end

  # ERROR HANDLING
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  #match '*path', to: 'errors#file_not_found', via: :all
  get 'errors/file_not_found' => "errors#file_not_found"
  get 'errors/unprocessable' => "errors#unprocessable"

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def new
		@user = User.friendly.find_by(id: params[:user])
	end

	def create
		@recipient = User.friendly.find_by(id: params[:user])
	    recipients = User.where(id: conversation_params[:recipients])
	    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
	    flash[:success] = "Your message was successfully sent!"
	    redirect_to conversation_path(conversation)
	end

	def show
	    @receipts = conversation.receipts_for(current_user)
	    # mark conversation as read
	    conversation.mark_as_read(current_user)
	end

	def reply
	    current_user.reply_to_conversation(conversation, message_params[:body])
	    flash[:notice] = "Your reply was successfully sent!"
	    redirect_to conversation_path(conversation)
  	end

  	def trash
    	conversation.move_to_trash(current_user)
    	redirect_to mailbox_inbox_path
  	end

  	def untrash
    	conversation.untrash(current_user)
    	redirect_to mailbox_inbox_path
  	end

		def empty_trash
		  current_user.mark_as_deleted(mailbox.trash.to_a)
		  redirect_to mailbox_inbox_path
			flash[:success] = "Trash messages deleted!"
		end

	private

	  def conversation_params
	    params.require(:conversation).permit(:subject, :body,recipients:[])
	  end

	  def message_params
	    params.require(:message).permit(:body, :subject)
	  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def recipients_options(chosen_recipient = nil)
	  s = ''
	  User.all.each do |user|
	    s << "<option value='#{user.id}' data-img-src='#{user.avatar.url(user.email, size: 50)}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
	  end
	  s.html_safe
	end
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <%= image_tag current_user.avatar.url(:thumb), :width => "64px" %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.subject %>
    </h4>
    Sent on <strong><%= conversation.messages.last.created_at.strftime("%A, %b %d, %Y") %></strong> at <strong><%= conversation.messages.last.created_at.strftime("%I:%M%p") %></strong>
    <br />
    <p><%= truncate conversation.messages.last.body, length: 145 %></p>
  </div>
  <p class="pull-right">
    <% if conversation.messages.last.is_unread?(current_user) %>
      <button class="btn btn-success">New!</button>
    <% end %>
    <%= link_to trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                              data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash"></i> Delete<% end %>
    <%= link_to conversation_path(conversation) do %> <button class="btn btn-primary"> <i class="fa fa-eye"></i> View Message</button><% end %>
  </p>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <% if params[:user].present? %>
        <%= f.label :recipients, 'Sending to ' %>
        <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, { :selected => @user.id }, { multiple: true, class: "form-control chosen-select" }) %>
      <% else %>
        <%= f.label :recipients %>
        <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true, class: "chosen-select form-control" }) %>
      <% end %>
    </div>
    <div class="form-group">
      <% if params[:subject].present? %>
        <%= f.label :subject %>
        <%= f.text_field :subject, value: params[:subject], class: "form-control" %>
      <% else %>
        <%= f.label :subject %>
        <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
      <% end %>
    </div>
    <div class="form-group">
      <% if params[:body].present? %>
        <%= f.text_area :body, class: 'form-control', rows: 4, value: params[:body] %>
      <% else %>
        <%= f.label :message %>
        <%= f.text_area :body, class: 'form-control', placeholder: "Type your message here", rows: 4  %>
      <% end %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-default col-md-12" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <%= image_tag message.sender.avatar.url(:thumb), :width => "64px" %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.subject %>
        </h4>
        Received on <strong><%= message.created_at.strftime("%A, %b %d, %Y") %> at <%= message.created_at.strftime("%I:%M%p") %></strong>
        <br /><br />
        <p><%= message.body %></p>
        <strong>
          <%= link_to root_url + "users/" + message.sender.slug + "/profile" do %>
            <%= message.sender.name %>
          <% end %>
        </strong>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<h3 class="text-center white">My Messages</h3>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<h3 class="text-center white">My Messages</h3>
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
        <br />
        <%= link_to "New Message", new_conversation_path, class: "btn btn-success col-md-12" %>
      </div>
    </div>
  </div>
 
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>

            <%= f.submit "Reply", class: 'btn btn-primary pull-right' %>

            <div class="pull-right">
              <% if conversation.is_trashed?(current_user) %>
                  <%= link_to 'Restore', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
              <% else %>
                  <%= link_to trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                              data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash"></i> Delete<% end %>
              <% end %>
              &nbsp;
            </div>

        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
 
</div>