config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :feeds do
    get "news", :action => :news, as: :news
    member do
     resources :entries, only: [:index, :show]
    end
  end

  resources :feeds
  resources :previews
  resources :activities
  resources :polls
  resources :pollvotes, only: [:create]


  resources :characters do
    get "characters/:page", :action => :index, :on => :collection
    get :autocomplete_character_creator, :on => :collection
    get :autocomplete_character_creator2, :on => :collection
    collection do
      get :all
    end
  end

  resources :collectibles do
    get "collectibles/:page", :action => :index, :on => :collection
    collection do
      get :all
    end
    resource :itemwish, module: :collectibles
    resource :itemown, module: :collectibles
    resource :itemsale, module: :collectibles
  end

  post '/rate' => 'rater#create', :as => 'rate'
  resources :books do
    get "books/:page", :action => :index, :on => :collection
    get :autocomplete_book_title, :on => :collection
    get :autocomplete_book_writer, :on => :collection
    get :autocomplete_book_writer2, :on => :collection
    get :autocomplete_book_artist, :on => :collection
    get :autocomplete_book_artist2, :on => :collection
    get :autocomplete_book_colors, :on => :collection
    get :autocomplete_book_cover, :on => :collection
    get :autocomplete_book_letters, :on => :collection
    get :autocomplete_book_editor, :on => :collection
    get :autocomplete_book_eic, :on => :collection
    get :autocomplete_book_country, :on => :collection
    get :autocomplete_book_publisher, :on => :collection
    get :autocomplete_book_imprint, :on => :collection
    get :autocomplete_book_retailer, :on => :collection
    get :autocomplete_book_convention, :on => :collection
    resources :comments
    collection do
      post :import
      get :autocomplete

      # Valiant
      get "valiant/keys" => "books#valiantkeys"
      get "valiant/all" => "books#valiantall"
      get "valiant/all/table" => "books#valiantalltbl"
      get "valiant/all/missing" => "books#valiantallmissing"
      get "valiant/all/table/missing" => "books#valiantalltblmissing"
      get "valiant/sketch" => "books#valiantsketch"
      get "valiant/sketch/table" => "books#valiantsketchtbl"
      get "valiant/trades" => "books#valianttrades"
      get "valiant/trades/table" => "books#valianttradestbl"

      # VH1 Valiant
      get "valiant/classic/all" => "books#valiantvh1all"
      get "valiant/classic/all/table" => "books#valiantvh1alltbl"
      get "valiant/classic/keys" => "books#valiantvh1keys"
      get "valiant/classic/all/missing" => "books#valiantvh1allmissing"
      get "valiant/classic/all/table/missing" => "books#valiantvh1alltblmissing"

      # VH2 Valiant
      get "valiant/acclaim/all" => "books#valiantvh2all"
      get "valiant/acclaim/all/table" => "books#valiantvh2alltbl"
      get "valiant/acclaim/all/missing" => "books#valiantvh2allmissing"
      get "valiant/acclaim/all/table/missing" => "books#valiantvh2alltblmissing"

      # International Valiant
      get "valiant/brazil/all" => "books#valiantbrazil"
      get "valiant/brazil/table" => "books#valiantbraziltbl"
      get "valiant/brazil/missing" => "books#valiantbrazilmissing"
      get "valiant/brazil/table/missing" => "books#valiantbraziltblmissing"
      get "valiant/canada/all" => "books#valiantcanada"
      get "valiant/canada/table" => "books#valiantcanadatbl"
      get "valiant/canada/missing" => "books#valiantcanadamissing"
      get "valiant/canada/table/missing" => "books#valiantcanadatblmissing"
      get "valiant/china/all" => "books#valiantchina"
      get "valiant/china/table" => "books#valiantchinatbl"
      get "valiant/china/missing" => "books#valiantchinamissing"
      get "valiant/china/table/missing" => "books#valiantchinatblmissing"
      get "valiant/france/all" => "books#valiantfrance"
      get "valiant/france/table" => "books#valiantfrancetbl"
      get "valiant/france/missing" => "books#valiantfrancemissing"
      get "valiant/france/table/missing" => "books#valiantfrancetblmissing"
      get "valiant/italy/all" => "books#valiantitaly"
      get "valiant/italy/table" => "books#valiantitalytbl"
      get "valiant/italy/missing" => "books#valiantitalymissing"
      get "valiant/italy/table/missing" => "books#valiantitalytblmissing"
      get "valiant/japan/all" => "books#valiantjapan"
      get "valiant/japan/table" => "books#valiantjapantbl"
      get "valiant/japan/missing" => "books#valiantjapanmissing"
      get "valiant/japan/table/missing" => "books#valiantjapantblmissing"
      get "valiant/mexico/all" => "books#valiantmexico"
      get "valiant/mexico/table" => "books#valiantmexicotbl"
      get "valiant/mexico/missing" => "books#valiantmexicomissing"
      get "valiant/mexico/table/missing" => "books#valiantmexicotblmissing"
      get "valiant/russia/all" => "books#valiantrussia"
      get "valiant/russia/table" => "books#valiantrussiatbl"
      get "valiant/russia/missing" => "books#valiantrussiamissing"
      get "valiant/russia/table/missing" => "books#valiantrussiatblmissing"
      get "valiant/turkey/all" => "books#valiantturkey"
      get "valiant/turkey/table" => "books#valiantturkeytbl"
      get "valiant/turkey/missing" => "books#valiantturkeymissing"
      get "valiant/turkey/table/missing" => "books#valiantturkeytblmissing"

      # Events Valiant
      get "valiant/events/4001ad" => "books#valiantevent4001ad"
      get "valiant/events/harbingerwars" => "books#valianteventshw"
      get "valiant/events/armorhunters" => "books#valianteventsah"
      get "valiant/events/bookofdeath" => "books#valianteventsbod"
      get "valiant/events/unity" => "books#valianteventsunity"
      get "valiant/events/chaoseffect" => "books#valianteventschaoseffect"
      get :manage
    end
    resource :wish, module: :books
    resource :own, module: :books
    resource :sale, module: :books
  end

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'omniauth_callbacks', sessions: 'sessions' }, :path => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  match '/users/:id' => 'users#destroy', :via => [:delete], :as => :admin_destroy_user
  match '/users/:id/profile' => "users#show", via: [:get], :as => 'profile'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/all' => 'users#all', via: [:get]
  match '/users/backers' => 'users#backers', via: [:get]
  match '/users/top25' => 'users#valianttop25', via: [:get]
  match '/users/leaderboard' => 'users#leaderboard', via: [:get]
  match '/users/:id/followers' => "users#followers", via: [:get], :as => 'followers'
  match '/users/:id/following' => "users#following", via: [:get], :as => 'following'
  get 'users/:id/notes' => 'books#mynotes', :as => 'notes'
  get 'users/:id/collection' => 'books#mybooks', :as => 'collection'
  get 'users/:id/collection/table' => 'books#mybookstbl', :as => 'collection_table'
  get 'users/:id/wishlist' => 'books#mywishlist', :as => 'wishlist'
  get 'users/:id/wishlist/table' => 'books#mywishlisttbl', :as => 'wishlist_table'
  get 'users/:id/forsale' => 'books#forsale', :as => 'forsale'
  get 'users/:id/forsale/table' => 'books#forsaletbl', :as => 'forsale_table'
  get 'users/emails' => 'users#emails', via: [:get]
  match 'follow' => 'users#follow', via: [:get]
  match 'unfollow' => 'users#unfollow', via: [:get]
  get 'switch_user' => 'switch_user#set_current_user'

  # Releases
  get 'nextweek' => 'books#thisweek'
  get 'releases/thisweek' => 'books#thisweek'
  get 'releases/currentweek' => 'books#currentweek'
  get 'releases/nextweek' => 'books#nextweek'
  get 'releases/solicitations' => 'books#solicitations'
  get 'releases/lastmonth' => 'books#lastmonth'
  get 'releases/thismonth' => 'books#thismonth'
  get 'releases/nextmonth' => 'books#nextmonth'
  get 'releases/twomonths' => 'books#monthafter'
  get 'releases/latestsolicitations' => 'books#latestsolicits'
  get 'releases/veibydate' => 'books#valiantreleasedate'
  get 'releases/veibydate/table' => 'books#valiantreleasedatetbl'
  get 'timelines/valiant' => 'pages#veitimeline'
  get 'releases/vh1bydate' => 'books#valiantvh1releasedate'
  get 'releases/vh1bydate/table' => 'books#valiantvh1releasedatetbl'
  get 'changelog' => 'pages#changelog'
  get 'supportus' => 'pages#supportus'

  # Sales
  get 'sales/monthly' => 'books#monthlysales'
  get 'sales/yearly' => 'books#yearlysales'
  get 'sales/marketshare' => 'pages#marketshare'
  get 'sales/vei' => 'books#valiantsalesvei'
  get 'sales/veibytitle' => 'books#valiantsalestitle'
  get 'sales/statistics' => 'books#valiantsalesstats'
  get 'sales/titlestatistics' => 'books#valiantsalesstatstitle'
  get 'sales/topselling' => 'books#valianttopselling'
  get 'values/topvalues' => 'books#valianttopvalues'
  get 'values/rankings' => 'books#valiantvalues'
  get 'values/missing' => 'books#valiantvaluesmissing'
  get 'feed' => 'books#feed'
  get 'allfeed' => 'books#allfeed'

  resources "contacts", only: [:new, :create]
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'search' => 'pages#search'
  get 'userlevels' => 'pages#levels'
  get 'news' => 'feeds#news', as: :news
  get 'chat' => 'pages#chat', as: :chat

  match 'sitemap', :to => 'sitemap#index', :via => [:get]

  # Mailbox routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "empty_trash", to: "conversations#empty_trash"

  resources :conversations do
    member do
      post :reply

app/models/character.rb
class Character < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :name, use: :slugged
	validates :name, presence: true
	has_attached_file :image, :styles => { :medium => "300x300>", 
										   :thumb => "150x150>" }, 
							  :convert_options => { 
                                           :medium => "-quality 75 -strip",
                                           :thumb => "-quality 75 -strip" },
							  :default_url => "https://s3.amazonaws.com/valiantdb/books/images/medium/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  autocomplete :character, :creator
  autocomplete :character, :creator2
  respond_to :html, :json, :js

  def new
    @character = Character.new
    respond_with(@character)
  end

  def edit
  end

  def create
    @character = Character.new(character_params)
    @character.save
    respond_with(@character)
  end

  def update
    @character = Character.friendly.find(params[:id])
    if @character.update_attributes!(character_params)
      respond_to do |format|
        format.html { redirect_to( @character )}
        format.json { render :json => @character }
      end
    else
      respond_to do |format|
        format.html { render :action  => :edit } # edit.html.erb
        format.json { render :nothing =>  true }
      end
    end
  end

  def destroy
    @character.destroy
    respond_with(@character)
  end

  def show
    @character = Character.friendly.find(params[:id])
    if @character.appera == "Current"
		@era = "2012-05-01"
		@era2 = Date.today
	elsif @character.appera == "Classic"
		@era = "1991-05-01"
		@era2 = "1996-09-30"
	else
		@era = "1996-10-01"
		@era2 = "2007-12-31"
	end
    respond_to do |format|
      format.html
      format.json { render :json => @character }
    end
  end

  def all
    @pgtitle = "All Characters"
    @tcount = Character.all.count
    @character = Character.all.order(name: :asc).page(params[:page]).per(24)
    respond_to do |format|
      format.html
      format.json { render json: @character }
      format.js
    end
  end

  private
	  def set_character
	     @character = Character.friendly.find(params[:id])
	  end

	  def character_params
	    params.require(:character).permit(:name, :image, :creator, :creator2, :apptitle, :appissue, :appera, :origin, :power, :power2, :power3, :power4, :power5, :slug)
	  end

end

app/helpers/character_helper.rb
module CharacterHelper
end

app/views/characters/_form.html.erb
  <div class="container">
    <% if @character.image.blank? %>
    <% else %>
      <span><%= image_tag @character.image.url(:thumb), class: "img-responsive img-thumbnail", :height => "100px" %></span>
    <% end %>
    <%= simple_form_for(@character, html: { class: "form-horizontal" }) do |f| %>
      <%= f.error_notification %>
      <%= f.full_error :image_file_size, class: "alert alert-error" %>
      <%= f.full_error :image_content_type, class: "alert alert-error" %>
      <div class="row">
        <div class="col-md-6">
          <% if @character.image.blank? %>
            <%= f.input :image, label: "Upload an image" %>
          <% else %>
            <%= f.input :image, label: "Change book image" %>
          <% end %>
            <ul class="list-unstyled">
              <li><%= f.input :name, label: false, placeholder: "Character name" %></li>
              <li><%= f.input :creator, :url => autocomplete_character_creator_characters_path, :as => :autocomplete, :label => false, placeholder: "Creator name (1)", class: "form-control" %></li>
              <% if current_user.super_admin? %>
                <li><%= f.input :creator2, :url => autocomplete_character_creator2_characters_path, :as => :autocomplete, label: false, placeholder: "Creator name (2)", class: "form-control" %></li>
              <% end %>
            </ul>
            <ul class="list-inline">
              <li><%= f.input :power %></li>
              <li><%= f.input :power2 %></li>
              <li><%= f.input :power3 %></li>
              <li><%= f.input :power4 %></li>
              <li><%= f.input :power5 %></li>
            </ul>
        </div>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-5">
          <% if current_user.super_admin? %>
            <h4>First appearance</h4>
            <ul class="list-inline">
              <li><%= f.input :apptitle, :label => "Title" %></li>
              <li><%= f.input :appissue, :label => "Issue" %></li>
              <li><%= f.input :appera, collection: ["Current", "Classic", "Acclaim"], include_blank: true %></li>
            </ul>
          <% end %> 
        </div>
        <div class="col-md-12">
          <%= f.input :origin, as: :text, input_html: { rows: "10" } %>
          <%= f.button :submit, data: {disable_with: "Saving..."} %>
        </div>
      </div>
    <% end %>
    <div class="clearfix"><br /></div>
    <%= link_to @character, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-remove"></i><% end %>
  </div>

app/views/characters/_modal.html.erb
<div class="text-center">
<%= image_tag @character.image.url, :alt => "#{@character.name}", class: "text-center img-responsive img-shadow", :id => "character-img" %>
</div>
<div class="text-left">
	<h2><%= @character.name %></h3>
	<p><strong>Created by</strong> <%= @character.creator %> and <%= @character.creator2 %></p>
	<p><strong>First appearance:</strong> 
		<%= @character.apptitle %> #<%= @character.appissue %> (<%= @character.appera %>)</p>
	<p><ul class="list-inline"><li><strong>Abilities:</strong> </li><li><%= @character.power %></li> <li><%= @character.power2 %></li> <li><%= @character.power3 %></li> <li><%= @character.power4 %></li> <li><%= @character.power5 %></li></ul></p>
	<h4>Origin</h4>
	<p><%= @character.origin %></p>
</div>

app/views/characters/all.html.erb
<div class="center">
  <div class="col-md-12 col-sm-12 col-xs-12">
  	<h4 class="white text-center">Valiant Characters <span class="label label-primary label-as-badge"><%= @character.count %></span></h4>
	<% if user_signed_in? %>
			<% @character.each do |c| %>
				<div class="col-md-3 col-sm-4 col-xs-12">
		            <div class="profile-sidebar2">
		                <!-- SIDEBAR USERPIC -->
		                <div class="profile-userpic">
		                	<%= image_tag c.image.url, :alt => c.name, class: "img-shadow", :width => "100%", :height => "100px" %>
		                </div>
		                <!-- END SIDEBAR USERPIC -->
		                <!-- SIDEBAR USER TITLE -->
		                <div class="profile-usertitle">
		                    <div class="profile-usertitle-name">
		                    	<div>
									&nbsp;
								</div>
		                        <%= link_to c do %>
		                        	<%= c.name %>
				                <% end %>
				                <br />
		                 		
		                    </div>
		                </div>
		                <!-- END SIDEBAR USER TITLE -->
		            </div>
		        </div>
			<% end %>
			<div class="clearfix"></div>
			<div class="text-center"><%= paginate @character %></div>
	<% else %>
		<h2 class="text-center">Oh, oh, you're not supposed to be here!</h2>
		<h3 class="text-center">Head <%= link_to "back home", root_path %>, I won't tell anyone you were here.</h3>
	<% end %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/characters/edit.html.erb
<div class="wellclear">
	<% if user_signed_in? && current_user.admin? %>
		Editing <%= @character.name %></h2>

		<%= render 'form' %>

		<%= link_to 'Show', @character %> 
	<% else %>
	<h1 class="text-center">You're not supposed to be here!</h1>
	<h2 class="text-center">Head back to <%= link_to "the database", root_url %>, I won't say anything.</h2>
	<% end %>
</div>

app/views/characters/new.html.erb
<div class="wellclear">
  <% if user_signed_in? && current_user.admin? %>
	<h1>New Character</h1>
	<%= render 'form' %>
  <% else %>
	<h1 class="text-center">You're not supposed to be here!</h1>
	<h2 class="text-center">Head back to <%= link_to "the database", root_url %>, I won't say anything.</h2>
  <% end %>
</div>

app/views/characters/show.html.erb
<div class="container">

	<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
		<%= image_tag @character.image.url, :alt => "#{@character.name}", class: "text-center img-responsive img-shadow", :id => "character-img", :width => "100%" %>
		<div class="wellclear">

			<div class="container">
				
				<h3 class="text-center"><%= @character.name %>
				</h3>


				<div class="col-md-8 col-sm-7 col-xs-12">
					<p><%= h @character.origin.html_safe %></p>
					<p>
						<ul class="list-inline">
							 <li><strong>Abilities:</strong></li>
							 <li><%= @character.power %></li> <li><%= @character.power2 %></li> <li><%= @character.power3 %></li> <li><%= @character.power4 %></li> 
							 <li><%= @character.power5 %></li>
						</ul>
					</p>
				</div>

				<div class="col-md-4 col-sm-5 col-xs-12">
					<p><strong>Creators:</strong><br /> <%= link_to search_path + "/?utf8=✓&query=" + @character.creator, data: { toggle: "tooltip" }, :title => "View books by " + @character.creator do %><%= @character.creator %><% end %><% if @character.creator2? %> and <%= link_to search_path + "/?utf8=✓&query=" + @character.creator2, data: { toggle: "tooltip" }, :title => "View books by " + @character.creator2 do %><%= @character.creator2 %><% end %><% end %><br /><br />
					   <strong>First appearance:</strong><br />
						<% if @character.appera == "Current" %>
							<% Book.where(:title => @character.apptitle, :issue => @character.appissue.to_s).where(:category => "Default").where("rdate > ?", "2012-05-01").each do |b| %>
								<%= link_to b do %><%= @character.apptitle %> #<%= @character.appissue.to_s %><% end %> (<%= @character.appera %>)
							<% end %>
						<% elsif @character.appera == "Classic" %>
							<% Book.where(:title => @character.apptitle, :issue => @character.appissue.to_s).where(:category => "Default").where("rdate < ?", "1996-09-30").each do |b| %>
								<%= link_to b do %><%= @character.apptitle %> #<%= @character.appissue.to_s %><% end %> (<%= @character.appera %>)
							<% end %>
						<% else %>
							<% Book.where(:title => @character.apptitle, :issue => @character.appissue.to_s).where(:category => "Default").where("rdate > ?", "1996-09-30").where("rdate < ?", "2004-12-31").each do |b| %>
								<%= link_to b do %><%= @character.apptitle %> #<%= @character.appissue.to_s %><% end %> (<%= @character.appera %>)
							<% end %>
						<% end %>
						<br /><br />
						<strong>Appearances:</strong> <% Tag.where(:name => @character.name).select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("tags.id").each do |t| %><%= t.count %> issues<% end %> </p>
				</div>

				<div class="pull-right">
					<% if user_signed_in? && current_user.admin? %>
						<%= link_to @character, method: :delete, data: { confirm: 'Are you sure?' } do %>
							<i class="fa fa-trash"></i>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>