config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :feeds do
    get "news", :action => :news, as: :news
    member do
     resources :entries, only: [:index, :show]
    end
  end

  resources :feeds
  resources :previews
  resources :activities
  resources :polls
  resources :pollvotes, only: [:create]


  resources :characters do
    get "characters/:page", :action => :index, :on => :collection
    get :autocomplete_character_creator, :on => :collection
    get :autocomplete_character_creator2, :on => :collection
    collection do
      get :all
    end
  end

  resources :collectibles do
    get "collectibles/:page", :action => :index, :on => :collection
    collection do
      get :all
    end
    resource :itemwish, module: :collectibles
    resource :itemown, module: :collectibles
    resource :itemsale, module: :collectibles
  end

  post '/rate' => 'rater#create', :as => 'rate'
  resources :books do
    get "books/:page", :action => :index, :on => :collection
    get :autocomplete_book_title, :on => :collection
    get :autocomplete_book_writer, :on => :collection
    get :autocomplete_book_writer2, :on => :collection
    get :autocomplete_book_artist, :on => :collection
    get :autocomplete_book_artist2, :on => :collection
    get :autocomplete_book_colors, :on => :collection
    get :autocomplete_book_cover, :on => :collection
    get :autocomplete_book_letters, :on => :collection
    get :autocomplete_book_editor, :on => :collection
    get :autocomplete_book_eic, :on => :collection
    get :autocomplete_book_country, :on => :collection
    get :autocomplete_book_publisher, :on => :collection
    get :autocomplete_book_imprint, :on => :collection
    get :autocomplete_book_retailer, :on => :collection
    get :autocomplete_book_convention, :on => :collection
    resources :comments
    collection do
      post :import
      get :autocomplete

      # Valiant
      get "valiant/keys" => "books#valiantkeys"
      get "valiant/all" => "books#valiantall"
      get "valiant/all/table" => "books#valiantalltbl"
      get "valiant/all/missing" => "books#valiantallmissing"
      get "valiant/all/table/missing" => "books#valiantalltblmissing"
      get "valiant/sketch" => "books#valiantsketch"
      get "valiant/sketch/table" => "books#valiantsketchtbl"
      get "valiant/trades" => "books#valianttrades"
      get "valiant/trades/table" => "books#valianttradestbl"

      # VH1 Valiant
      get "valiant/classic/all" => "books#valiantvh1all"
      get "valiant/classic/all/table" => "books#valiantvh1alltbl"
      get "valiant/classic/keys" => "books#valiantvh1keys"
      get "valiant/classic/all/missing" => "books#valiantvh1allmissing"
      get "valiant/classic/all/table/missing" => "books#valiantvh1alltblmissing"

      # VH2 Valiant
      get "valiant/acclaim/all" => "books#valiantvh2all"
      get "valiant/acclaim/all/table" => "books#valiantvh2alltbl"
      get "valiant/acclaim/all/missing" => "books#valiantvh2allmissing"
      get "valiant/acclaim/all/table/missing" => "books#valiantvh2alltblmissing"

      # International Valiant
      get "valiant/brazil/all" => "books#valiantbrazil"
      get "valiant/brazil/table" => "books#valiantbraziltbl"
      get "valiant/brazil/missing" => "books#valiantbrazilmissing"
      get "valiant/brazil/table/missing" => "books#valiantbraziltblmissing"
      get "valiant/canada/all" => "books#valiantcanada"
      get "valiant/canada/table" => "books#valiantcanadatbl"
      get "valiant/canada/missing" => "books#valiantcanadamissing"
      get "valiant/canada/table/missing" => "books#valiantcanadatblmissing"
      get "valiant/china/all" => "books#valiantchina"
      get "valiant/china/table" => "books#valiantchinatbl"
      get "valiant/china/missing" => "books#valiantchinamissing"
      get "valiant/china/table/missing" => "books#valiantchinatblmissing"
      get "valiant/france/all" => "books#valiantfrance"
      get "valiant/france/table" => "books#valiantfrancetbl"
      get "valiant/france/missing" => "books#valiantfrancemissing"
      get "valiant/france/table/missing" => "books#valiantfrancetblmissing"
      get "valiant/italy/all" => "books#valiantitaly"
      get "valiant/italy/table" => "books#valiantitalytbl"
      get "valiant/italy/missing" => "books#valiantitalymissing"
      get "valiant/italy/table/missing" => "books#valiantitalytblmissing"
      get "valiant/japan/all" => "books#valiantjapan"
      get "valiant/japan/table" => "books#valiantjapantbl"
      get "valiant/japan/missing" => "books#valiantjapanmissing"
      get "valiant/japan/table/missing" => "books#valiantjapantblmissing"
      get "valiant/mexico/all" => "books#valiantmexico"
      get "valiant/mexico/table" => "books#valiantmexicotbl"
      get "valiant/mexico/missing" => "books#valiantmexicomissing"
      get "valiant/mexico/table/missing" => "books#valiantmexicotblmissing"
      get "valiant/russia/all" => "books#valiantrussia"
      get "valiant/russia/table" => "books#valiantrussiatbl"
      get "valiant/russia/missing" => "books#valiantrussiamissing"
      get "valiant/russia/table/missing" => "books#valiantrussiatblmissing"
      get "valiant/turkey/all" => "books#valiantturkey"
      get "valiant/turkey/table" => "books#valiantturkeytbl"
      get "valiant/turkey/missing" => "books#valiantturkeymissing"
      get "valiant/turkey/table/missing" => "books#valiantturkeytblmissing"

      # Events Valiant
      get "valiant/events/4001ad" => "books#valiantevent4001ad"
      get "valiant/events/harbingerwars" => "books#valianteventshw"
      get "valiant/events/armorhunters" => "books#valianteventsah"
      get "valiant/events/bookofdeath" => "books#valianteventsbod"
      get "valiant/events/unity" => "books#valianteventsunity"
      get "valiant/events/chaoseffect" => "books#valianteventschaoseffect"
      get :manage
    end
    resource :wish, module: :books
    resource :own, module: :books
    resource :sale, module: :books
  end

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'omniauth_callbacks', sessions: 'sessions' }, :path => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  match '/users/:id' => 'users#destroy', :via => [:delete], :as => :admin_destroy_user
  match '/users/:id/profile' => "users#show", via: [:get], :as => 'profile'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  match '/users/all' => 'users#all', via: [:get]
  match '/users/backers' => 'users#backers', via: [:get]
  match '/users/top25' => 'users#valianttop25', via: [:get]
  match '/users/leaderboard' => 'users#leaderboard', via: [:get]
  match '/users/:id/followers' => "users#followers", via: [:get], :as => 'followers'
  match '/users/:id/following' => "users#following", via: [:get], :as => 'following'
  get 'users/:id/notes' => 'books#mynotes', :as => 'notes'
  get 'users/:id/collection' => 'books#mybooks', :as => 'collection'
  get 'users/:id/collection/table' => 'books#mybookstbl', :as => 'collection_table'
  get 'users/:id/wishlist' => 'books#mywishlist', :as => 'wishlist'
  get 'users/:id/wishlist/table' => 'books#mywishlisttbl', :as => 'wishlist_table'
  get 'users/:id/forsale' => 'books#forsale', :as => 'forsale'
  get 'users/:id/forsale/table' => 'books#forsaletbl', :as => 'forsale_table'
  get 'users/emails' => 'users#emails', via: [:get]
  match 'follow' => 'users#follow', via: [:get]
  match 'unfollow' => 'users#unfollow', via: [:get]
  get 'switch_user' => 'switch_user#set_current_user'

  # Releases
  get 'nextweek' => 'books#thisweek'
  get 'releases/thisweek' => 'books#thisweek'
  get 'releases/currentweek' => 'books#currentweek'
  get 'releases/nextweek' => 'books#nextweek'
  get 'releases/solicitations' => 'books#solicitations'
  get 'releases/lastmonth' => 'books#lastmonth'
  get 'releases/thismonth' => 'books#thismonth'
  get 'releases/nextmonth' => 'books#nextmonth'
  get 'releases/twomonths' => 'books#monthafter'
  get 'releases/latestsolicitations' => 'books#latestsolicits'
  get 'releases/veibydate' => 'books#valiantreleasedate'
  get 'releases/veibydate/table' => 'books#valiantreleasedatetbl'
  get 'timelines/valiant' => 'pages#veitimeline'
  get 'releases/vh1bydate' => 'books#valiantvh1releasedate'
  get 'releases/vh1bydate/table' => 'books#valiantvh1releasedatetbl'
  get 'changelog' => 'pages#changelog'
  get 'supportus' => 'pages#supportus'

  # Sales
  get 'sales/monthly' => 'books#monthlysales'
  get 'sales/yearly' => 'books#yearlysales'
  get 'sales/marketshare' => 'pages#marketshare'
  get 'sales/vei' => 'books#valiantsalesvei'
  get 'sales/veibytitle' => 'books#valiantsalestitle'
  get 'sales/statistics' => 'books#valiantsalesstats'
  get 'sales/titlestatistics' => 'books#valiantsalesstatstitle'
  get 'sales/topselling' => 'books#valianttopselling'
  get 'values/topvalues' => 'books#valianttopvalues'
  get 'values/rankings' => 'books#valiantvalues'
  get 'values/missing' => 'books#valiantvaluesmissing'
  get 'feed' => 'books#feed'
  get 'allfeed' => 'books#allfeed'

  resources "contacts", only: [:new, :create]
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'search' => 'pages#search'
  get 'userlevels' => 'pages#levels'
  get 'news' => 'feeds#news', as: :news
  get 'chat' => 'pages#chat', as: :chat

  match 'sitemap', :to => 'sitemap#index', :via => [:get]

  # Mailbox routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "empty_trash", to: "conversations#empty_trash"

  resources :conversations do
    member do
      post :reply

app/models/collectible.rb
class Collectible < ActiveRecord::Base
	validates :title, presence: true
	has_attached_file :image, :styles => { :medium => "300x300>", 
										   :thumb => "150x150>", 
										   :mini => "36x36>" }, 
							  :convert_options => { 
                                           :medium => "-quality 75 -strip",
                                           :thumb => "-quality 75 -strip", 
                                           :mini => "-quality 75 -strip" },
							  :default_url => "https://s3.amazonaws.com/valiantdb/books/images/medium/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_many :itemwishes, :dependent => :destroy
	has_many :itemowns, :dependent => :destroy
	has_many :itemsales, :dependent => :destroy

	def to_param
		"#{id}-#{title.to_s.parameterize}-#{rdate.strftime("%Y")}"
	end

	def price_in_dollars
		price.to_d/100 if price
	end

	def price_in_dollars=(dollars)
		self.price = dollars.to_d*100 if dollars.present?
	end
	
end

app/controllers/collectibles/itemowns_controller.rb
class Collectibles::ItemownsController < ApplicationController
	before_action :set_collectible
	skip_before_action :verify_authenticity_token
	respond_to :html, :json, :js

	def create
		(@collectible.itemowns.where(user_id: current_user.id).first_or_create)
		if user_signed_in? && current_user.itemwishes?(@collectible)
			@collectible.itemwishes.where(user_id: current_user.id).destroy_all
		end
		@itemown = Itemown.where(user_id: current_user.id, collectible_id: @collectible.id)
		respond_to do |format|
			format.html { redirect_to request.referer}
			format.js
		end
	end

	def update
	  @itemown = @collectible.itemowns.where(user_id: current_user.id)
	  Itemown.update(@itemown, itemown_params)
	  redirect_to request.referer
	  flash[:notice] = "Update successful!"
	end

	def show
		redirect_to @collectible
	end

	def destroy
		@collectible.itemowns.where(user_id: current_user.id).destroy_all
		respond_to do |format|
			format.html { redirect_to @collectible}
			format.js
		end
	end

	private
		def set_collectible
			@collectible = Collectible.find(params[:collectible_id])
		end

		def itemown_params
			params.require(:itemown).permit(:quantity)
		end
end

app/controllers/collectibles/itemsales_controller.rb
class Collectibles::ItemsalesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_collectible

	def create
		if Rails.env.production?
			(@collectible.itemsales.where(user_id: current_user.id).first_or_create).create_activity :create, owner: current_user, recipient: :collectible
		else
			(@collectible.itemsales.where(user_id: current_user.id).first_or_create).create_activity :create, owner: current_user, recipient: :collectible
		end
		User.where.not(id: current_user.id).each do |u|
			u.wished_collectibles.where(:id => @collectible.id).each do
				current_user.send_message(
				u,
				"The user below has posted " + @collectible.title.to_s + " for sale and this item is on your wishlist. By replying, you will be put into contact with the seller to further inquire about this item. All sales are the responsibility of the buyer/seller and not of Valiant Database or anyone involved with the development of the site.",
				"FS " + @collectible.title.to_s )
			end
		end
		respond_to do |format|
			format.html { redirect_to @collectible}
			format.js
		end
	end

	def destroy
		@collectible.itemsales.where(user_id: current_user.id).destroy_all
		respond_to do |format|
			format.html { redirect_to @collectible}
			format.js
		end
	end

	private
		def set_collectible
			@collectible = Collectible.find(params[:collectible_id])
		end
end

app/controllers/collectibles/itemwishes_controller.rb
class Collectibles::ItemwishesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_collectible

	def create
		if Rails.env.production?
			(@collectible.itemwishes.where(user_id: current_user.id).first_or_create).create_activity :create, owner: current_user, recipient: :collectible
		else
			(@collectible.itemwishes.where(user_id: current_user.id).first_or_create).create_activity :create, owner: current_user, recipient: :collectible
		end
		unless @collectible.rdate.future?
			User.where.not(id: current_user.id).each do |u|
				u.forsale_collectibles.where(:id => @collectible.id).each do
					current_user.send_message(
					u,
					"The user below has added " + @collectible.title.to_s + " to their wishlist and you have one for sale. By replying, you will be put into contact with the potential buyer. All sales are the responsibility of the buyer/seller and not of Valiant Database or anyone involved with the development of the site.",
					"Looking for " + @collectible.title.to_s )
				end
			end
		end
		respond_to do |format|
			format.html { redirect_to @collectible }
			format.js
		end
	end

	def destroy
		@collectible.itemwishes.where(user_id: current_user.id).destroy_all
		respond_to do |format|
			format.html { redirect_to @collectible}
			format.js
		end
	end

	private
		def set_collectible
			@collectible = Collectible.find(params[:collectible_id])
		end

end

app/controllers/collectibles_controller.rb
class CollectiblesController < ApplicationController
  before_action :set_collectible, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :js

  def new
    @collectible = Collectible.new
    respond_with(@collectible)
  end

  def edit
  end

  def create
    @collectible = Collectible.new(collectible_params)
    @collectible.save
    respond_with(@collectible)
  end

  def update
    @collectible = Collectible.find(params[:id])
    if @collectible.update_attributes!(collectible_params)
      respond_to do |format|
        format.html { redirect_to( @collectible )}
        format.json { render :json => @collectible }
      end
    else
      respond_to do |format|
        format.html { render :action  => :edit } # edit.html.erb
        format.json { render :nothing =>  true }
      end
    end
  end

  def destroy
    @collectible.destroy
    respond_with(@collectible)
  end

  def show
    @collectible = Collectible.find(params[:id])
    @ownusers = User.joins(:itemowns).where("itemowns.collectible_id = ?", @collectible.id).includes(:itemowns).order("itemowns.quantity asc")
    respond_to do |format|
      format.html
      format.json { render :json => @collectible }
    end
  end

  def all
    @pgtitle = "All Collectibles"
    @tcount = Collectible.all.count
    @collectible = Collectible.all.order(title: :asc).page(params[:page]).per(24)
    respond_to do |format|
      format.html
      format.json { render json: @collectible }
      format.js
    end
  end

  private
	  def set_collectible
	     @collectible = Collectible.find(params[:id])
	  end

	  def collectible_params
	    params.require(:collectible).permit(:title, :rdate, :description, :manufacturer, :link, :image, :slug, :price, :price_in_dollars, :printrun, :category)
	  end

end

app/views/collectibles/_form.html.erb
  <div class="container">
    <% if @collectible.image.blank? %>
    <% else %>
      <span><%= image_tag @collectible.image.url(:thumb), class: "img-responsive img-thumbnail", :height => "100px" %></span>
    <% end %>
    <%= simple_form_for(@collectible, html: { class: "form-horizontal" }) do |f| %>
      <%= f.error_notification %>
      <%= f.full_error :image_file_size, class: "alert alert-error" %>
      <%= f.full_error :image_content_type, class: "alert alert-error" %>
      <div class="row">
        <div class="col-md-6">
          <% if @collectible.image.blank? %>
            <%= f.input :image, label: "Upload an image" %>
          <% else %>
            <%= f.input :image, label: "Change book image" %>
          <% end %>
            <ul class="list-unstyled">
              <li><%= f.input :title, label: false, placeholder: "Collectible name" %></li>
              <li><%= f.input :manufacturer, :label => false, placeholder: "Manufacturer", class: "form-control" %></li>
              <li><%= f.input :category, label: false, collection: ["Lithograph", "Minimates", "Plush", "Poster", "Shot Glass", "Standee", "Statue", "Vinyl"], include_blank: true %></li>
              <li><%= f.input :price_in_dollars, label: false, placeholder: "Price" %></li>
              <li><%= f.input :printrun, label: false, placeholder: "Print Run" %></li>
            </ul>
            <ul class="list-inline">
              <li><%= f.input :rdate, :label => "Release date", as: :date, start_year: Date.today.year - 30 %></li>
            </ul>
        </div>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-12">
          <%= f.input :link, as: :text, input_html: { rows: "1" } %>
          <%= f.input :description, as: :text, input_html: { rows: "3" } %>
          <%= f.button :submit, data: {disable_with: "Saving..."} %>
        </div>
      </div>
    <% end %>
    <div class="clearfix"><br /></div>
    <%= link_to @collectible, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-remove"></i><% end %>
  </div>

app/views/collectibles/_itemowns.html.erb
<% if user_signed_in? && current_user.itemowns?(@collectible) %>
	<%= link_to collectible_itemown_path(@collectible), method: :delete, remote: true, class: "btn btn-danger btn-circle", title: "Remove from collection", data: { toggle: "tooltip", disable_with: "<span class='fa fa-minus'></span>"} do %><span class="fa fa-heart-o"></span><% end %>
<% else %>
	<%= link_to collectible_itemown_path(@collectible), method: :post, remote: true, class: "btn btn-success btn-circle", title: "Add to collection", data: { toggle: "tooltip", disable_with: "<span class='fa fa-plus'></span>"} do %><span class="fa fa-heart"></span><% end %>
<% end %>

app/views/collectibles/_itemownsrating.html.erb
<% if user_signed_in? %>
	<p>Your rating: <%= rating_for @collectible, "collectible", disable_after_rate: false, cancel_hint: 'Reset vote', enable_half: true  %></p>
	<br />
<% end %>

app/views/collectibles/_itemsales.html.erb
<% if user_signed_in? && current_user.itemowns?(@collectible) %>	
	<% if user_signed_in? && current_user.itemsales?(@collectible) %>
		<%= link_to collectible_itemsale_path(@collectible), method: :delete, remote: true, class: "btn btn-warning btn-circle", title: "Remove from sales", data: { toggle: "tooltip", disable_with: "<span class='fa fa-minus'></span>"} do %><span class="fa fa-dollar"></span><% end %>
	<% else %>
		<%= link_to collectible_itemsale_path(@collectible), method: :post, remote: true, class: "btn btn-default btn-circle", title: "Mark for sale", data: { toggle: "tooltip", disable_with: "<span class='fa fa-plus'></span>"} do %><span class="fa fa-dollar"></span><% end %>
	<% end %>
<% end %>

app/views/collectibles/_itemwishes.html.erb
	<% if user_signed_in? && current_user.itemwishes?(@collectible) %>
		<%= link_to collectible_itemwish_path(@collectible), method: :delete, remote: true, class: "btn btn btn-danger btn-circle", title: "Remove from wishlist", data: { toggle: "tooltip", disable_with: "<span class='fa fa-minus'></span>"} do %><span class="fa fa-star-o"></span><% end %>
	<% else %>
		<%= link_to collectible_itemwish_path(@collectible), method: :post, remote: true, class: "btn btn-success btn-circle", title: "Add to wishlist", data: { toggle: "tooltip", disable_with: "<span class='fa fa-plus'></span>"} do %><span class="fa fa-star"></span><% end %>
	<% end %>

app/views/collectibles/show.html.erb
<% if controller_name == "collectibles" && action_name == "show" %>
    <div itemscope itemtype="http://schema.org/Book" class="hidden">
      <meta itemprop="description" content="<%= @collectible.description %>">
        <meta itemprop="datePublished" content="<%= @collectible.rdate.strftime("%B %d, %Y") %>">
        <link itemprop="url" href="http://www.valiantdatabase.com/collectibles/<%= @collectible.id.to_s %>" rel="author"/>
  		<img itemprop="image" src="<%= @collectible.image.url(:thumb) %>" alt="<%= @collectible.id.to_s %>" />
        <a itemprop="url" href="http://www.valiantdatabase.com/collectibles/<%= @collectible.id.to_s %>"><span itemprop="name" style="display:block;"><strong><%= @collectible.title %></strong></span></a>
        <span itemprop="author" itemscope itemtype="http://schema.org/Person" style="display:block;"><span itemprop="name"><%= @collectible.manufacturer %></span></span>
  </div>
<% end %>

<div class="container">
    <div class="row">
    	<div class="col-md-4 col-sm-6 col-xs-12">
            <!-- begin macbook pro mockup -->
            <div class="md-glare">
                <div class="md-lid">
                    <div class="md-screen">
                    <!-- content goes here -->                
                        <div class="tab-featured-image">
                            <div class="tab-content">
                                <div class="tab-pane  in active" id="tab1">
	                                	<%= link_to @collectible.image.url(:original), :title => @collectible.title, class: "fancybox" do %>
	                                    	<%= image_tag @collectible.image.url(:original), :alt => @collectible.title, class: "img-responsive img-shadow" %>
	                                    <% end %>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="md-base"></div>
            </div> <!-- end macbook pro mockup -->

        </div> <!-- / .col-md-6 -->

        <div class="col-md-6 col-sm-6 col-xs-12">
            <!-- begin panel group -->
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                
                <!-- panel 1 -->
                <div class="panel panel-default">
                    <!--wrap panel heading in span to trigger image change as well as collapse -->
                    <span class="side-tab" data-target="#tab1" data-toggle="tab" role="tab" aria-expanded="false">
                        <div class="panel-heading" role="tab" id="headingOne"data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <h4>
	                            <%= @collectible.title %>
							</h4>
                        </div>
                    </span>
                    
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
	                    <div class="panel-body">
	                        	<!-- Tab content goes here -->
                                <ul class="list-unstyled pull-right">
                                        <% if user_signed_in? %>
                                            <% unless @collectible.rdate.future? %>
                                                <li id="<%= @collectible.id %>_owns">
                                                    <%= render partial: "itemowns" %>
                                                </li>
                                            <% end %>
                                            <li id="<%= @collectible.id %>_wishes">
                                                <%= render partial: "itemwishes" %>
                                            </li>
                                            <!-- <li id="<%= @collectible.id %>_sales">
                                                    <%= render partial: "itemsales" %>
                                            </li> -->
                                        <% end %>
                                </ul>

	                        	<p>
	                        		
	                        		<% if @collectible.rdate.future? %>
										Will be released <%= @collectible.rdate.strftime("%B %d, %Y") %>
			 						<% else %>
										Released on <%= @collectible.rdate.strftime("%B %d, %Y") %>
									<% end %>
									<br />
									Manufactured by <%= @collectible.manufacturer %><br />
									<strong>Category:</strong> <%= @collectible.category %><br />
									<% if @collectible.price? %>
										<strong>Price:</strong> $<%= "%.2f" % @collectible.price_in_dollars %>
									<% end %>
                                    <% if @collectible.category == "Statue" %>
                                        <% if @ownusers.count > 0 %>
                                            <br />
                                            <strong>Owned by:</strong> 
                                            <a href="#" data-toggle="modal" data-target="#collectible_owners">
                                                <%= @ownusers.count %> 
                                                <% if @ownusers.count == 1 %>user<% else %>users<% end %>
                                            </a>
                                        <% end %>
                                    <% end %>
								</p>

                                <% if user_signed_in? %>
                                    <% if @collectible.category == "Statue" %>
                                        <span id="<%= @collectible.id %>_quantity">
                                            <%= render 'collectibles/itemownsquantity' %>
                                        </span>
                                    <% end %>
                                <% end %>
								
								<div class="clearfix"></div>
								<p>
									<strong>Description:</strong>
									<% if @collectible.description.blank? %>
										No notes for this item. 
									<% else %>
										<%= h @collectible.description.html_safe %>
									<% end %>				
								</p>

								<%= link_to @collectible.link, data: { toggle: "tooltip" }, :title => "Click to purchase this item", class: "btn btn-default btn-sm", :target => "_blank" do %><span class="fa fa-shopping-cart"></span> Purchase this item<% end %>

								<% if user_signed_in? && current_user.patron? %>
								<% else %>
									<%= link_to supportus_path, :title => "Support us", class: "btn btn-default btn-sm", :target => "_blank" do %>
										<span class="fa fa-diamond"></span> Support Us
									<% end %>
								<% end %>

                                <!-- Wishers Modal -->
                                <div class="modal fade" id="collectible_owners" tabindex="-1" role="dialog" aria-labelledby="collectible_ownersLabel">
                                  <br />
                                  <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h5 class="modal-title" id="myModalLabel">Users who own this</h5>
                                      </div>
                                      <div class="modal-body">
                                        <% @ownusers.each do |w| %>
                                                <div class="col-md-3 col-sm-4 col-xs-6">
                                                    <% if w.avatar.blank? %>
                                                        <%= link_to root_url + "users/" + w.slug.to_s + "/collection", :title => w.name.to_s + "'s Collection" do %>
                                                            <img src="https://s3.amazonaws.com/valiantdb/images/noimage2.jpg" class="img-responsive">
                                                        <% end %>
                                                    <% else %>
                                                        <%= link_to root_url + "users/" + w.slug.to_s + "/collection", :title => w.name.to_s + "'s Collection" do %>
                                                            <%= image_tag w.avatar.url(:medium), :alt => "Profile image", class: "img-responsive" %>
                                                        <% end %>
                                                    <% end %>
                                                    <% w.itemowns.each do |q| %><span class="col-md-12 col-md-offset-2 col-sm-12 col-sm-offset-4 col-xs-12 col-xs-offset-3">#<%= q.quantity %></span><% end %>
                                                    <br />
                                                </div>
                                        <% end %>
                                      </div>
                                      <div class="clearfix"></div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>
	                    </div>

                    </div>

                </div> 
                <!-- / panel 1 -->

        </div> <!-- /col-md-6 -->
    </div> <!--/ .row -->
</div> <!-- end sidetab container -->
</div>
<div class="clearfix"><br /></div>